/**
 * ITEM & MUTATION TRACKER
 * Shared Item Database & Mutations Registry
 */

var MUTATIONS = [
    { id: "polished", name: "Polished", rate: "23.620%", colorClass: "polished" },
    { id: "bubbly", name: "Bubbly", rate: "19.027%", colorClass: "bubbly" },
    { id: "pearly", name: "Pearly", rate: "15.327%", colorClass: "pearly" },
    { id: "frosted", name: "Frosted", rate: "12.539%", colorClass: "frosted" },
    { id: "glowing", name: "Glowing", rate: "9.713%", colorClass: "glowing" },
    { id: "sparkly", name: "Sparkly", rate: "7.433%", colorClass: "sparkly" },
    { id: "surged", name: "Surged", rate: "5.515%", colorClass: "surged" },
    { id: "fiery", name: "Fiery", rate: "3.490%", colorClass: "fiery" },
    { id: "eclipsed", name: "Eclipsed", rate: "1.917%", colorClass: "eclipsed" },
    { id: "glitched", name: "Glitched", rate: "0.901%", colorClass: "glitched" },
    { id: "corrupted", name: "Corrupted", rate: "0.389%", colorClass: "corrupted" },
    { id: "akashic", name: "Akashic", rate: "0.130%", colorClass: "akashic" }
];

var BASE_ITEMS = [
    // COMMON (19)
    { id: "basic_adder", name: "Basic Adder", rarity: "Common" },
    { id: "basic_multiplier", name: "Basic Multiplier", rarity: "Common" },
    { id: "fishbone_adder", name: "Fishbone Adder", rarity: "Common" },
    { id: "puzzle_adder", name: "Puzzle Adder", rarity: "Common" },
    { id: "soccer_adder", name: "Soccer Adder", rarity: "Common" },
    { id: "traffic_cone_adder", name: "Traffic Cone Adder", rarity: "Common" },
    { id: "basic_dropper", name: "Basic Dropper", rarity: "Common" },
    { id: "basic_furnace", name: "Basic Furnace", rarity: "Common" },
    { id: "copper_dropper", name: "Copper Dropper", rarity: "Common" },
    { id: "network_furnace", name: "Network Furnace", rarity: "Common" },
    { id: "pizza_multiplier", name: "Pizza Multiplier", rarity: "Common" },
    { id: "candle_multiplier", name: "Candle Multiplier", rarity: "Common" },
    { id: "jb_adder", name: "JB Adder", rarity: "Common" },
    { id: "ice_cream_multiplier", name: "Ice Cream Multiplier", rarity: "Common", isJunkyard: true },
    { id: "cassette_multiplier", name: "Cassette Multiplier", rarity: "Common", isJunkyard: true },
    { id: "domino_adder", name: "Domino Adder", rarity: "Common", isJunkyard: true },
    { id: "larp_sahur", name: "Larp Sahur", rarity: "Common", isJunkyard: true },
    { id: "electric_fan_multiplier", name: "Electric Fan Multiplier", rarity: "Common", isJunkyard: true },
    { id: "hairdryer_adder", name: "Hairdryer Adder", rarity: "Common", isJunkyard: true },

    // UNCOMMON (17)
    { id: "hippo_adder", name: "Hippo Adder", rarity: "Uncommon" },
    { id: "magnifying_multiplier", name: "Magnifying Multiplier", rarity: "Uncommon" },
    { id: "ultra_adder", name: "Ultra Adder", rarity: "Uncommon" },
    { id: "cheesestick_adder", name: "Cheesestick Adder", rarity: "Uncommon" },
    { id: "hot_sauce_multiplier", name: "Hot Sauce Multiplier", rarity: "Uncommon" },
    { id: "firework_multiplier", name: "Firework Multiplier", rarity: "Uncommon" },
    { id: "lemon_adder", name: "Lemon Adder", rarity: "Uncommon" },
    { id: "science_furnace", name: "Science Furnace", rarity: "Uncommon" },
    { id: "tin_dropper", name: "Tin Dropper", rarity: "Uncommon" },
    { id: "gold_dropper", name: "Gold Dropper", rarity: "Uncommon" },
    { id: "yo_yo_multiplier", name: "Yo-yo Multiplier", rarity: "Uncommon" },
    { id: "tombstone_adder", name: "Tombstone Adder", rarity: "Uncommon" },
    { id: "toilet_paper_multiplier", name: "Toilet Paper Multiplier", rarity: "Uncommon", isJunkyard: true },
    { id: "toilet_dropper", name: "Toilet Dropper", rarity: "Uncommon", isJunkyard: true },
    { id: "teddy_bear_adder", name: "Teddy Bear Adder", rarity: "Uncommon", isJunkyard: true },
    { id: "fidget_spinner_multiplier", name: "Fidget Spinner Multiplier", rarity: "Uncommon", isJunkyard: true },
    { id: "paperclip_multiplier", name: "Paperclip Multiplier", rarity: "Uncommon", isJunkyard: true },

    // RARE (19)
    { id: "sandcastle_multiplier", name: "Sandcastle Multiplier", rarity: "Rare" },
    { id: "chess_adder", name: "Chess Adder", rarity: "Rare" },
    { id: "headphones_multiplier", name: "Headphones Multiplier", rarity: "Rare" },
    { id: "cake_adder", name: "Cake Adder", rarity: "Rare" },
    { id: "igloo_multiplier", name: "Igloo Multiplier", rarity: "Rare" },
    { id: "mushroom_adder", name: "Mushroom Adder", rarity: "Rare" },
    { id: "goalie_furnace", name: "Goalie Furnace", rarity: "Rare" },
    { id: "cactus_furnace", name: "Cactus Furnace", rarity: "Rare" },
    { id: "sapphire_dropper", name: "Sapphire Dropper", rarity: "Rare" },
    { id: "cheese_dropper", name: "Cheese Dropper", rarity: "Rare" },
    { id: "rubber_ducky_multiplier", name: "Rubber Ducky Multiplier", rarity: "Rare" },
    { id: "donut_adder", name: "Donut Adder", rarity: "Rare" },
    { id: "ping_pong_multiplier", name: "Ping Pong Multiplier", rarity: "Rare" },
    { id: "vacuum_adder", name: "Vacuum Adder", rarity: "Rare" },
    { id: "strawberry_adder", name: "Strawberry Adder", rarity: "Rare" },
    { id: "toast_adder", name: "Toast Adder", rarity: "Rare", isJunkyard: true },
    { id: "hot_tub_furnace", name: "Hot Tub Furnace", rarity: "Rare", isJunkyard: true },
    { id: "snail_multiplier", name: "Snail Multiplier", rarity: "Rare", isJunkyard: true },
    { id: "burger_adder", name: "Burger Adder", rarity: "Rare", isJunkyard: true },
    { id: "anchor_adder", name: "Anchor Adder", rarity: "Rare", isJunkyard: true },

    // EPIC (18)
    { id: "cat_multiplier", name: "Cat Multiplier", rarity: "Epic" },
    { id: "watering_can_adder", name: "Watering Can Adder", rarity: "Epic" },
    { id: "camera_multiplier", name: "Camera Multiplier", rarity: "Epic" },
    { id: "snowman_multiplier", name: "Snowman Multiplier", rarity: "Epic" },
    { id: "bamboo_adder", name: "Bamboo Adder", rarity: "Epic" },
    { id: "pumpkin_adder", name: "Pumpkin Adder", rarity: "Epic" },
    { id: "ufo_adder", name: "Ufo Adder", rarity: "Epic" },
    { id: "emerald_dropper", name: "Emerald Dropper", rarity: "Epic" },
    { id: "willow_dropper", name: "Willow Dropper", rarity: "Epic" },
    { id: "lunar_furnace", name: "Lunar Furnace", rarity: "Epic" },
    { id: "ouroboros_multiplier", name: "Ouroboros Multiplier", rarity: "Epic" },
    { id: "pot_of_gold_furnace", name: "Pot Of Gold Furnace", rarity: "Epic" },
    { id: "lightning_furnace", name: "Lightning Furnace", rarity: "Epic" },
    { id: "dog_adder", name: "Dog Adder", rarity: "Epic" },
    { id: "horseshoe_multiplier", name: "Horseshoe Multiplier", rarity: "Epic", isJunkyard: true },
    { id: "guillotine_multiplier", name: "Guillotine Multiplier", rarity: "Epic", isJunkyard: true },
    { id: "paintbrush_multiplier", name: "Paintbrush Multiplier", rarity: "Epic", isJunkyard: true },
    { id: "skateboard_multiplier", name: "Skateboard Multiplier", rarity: "Epic", isJunkyard: true },

    // LEGENDARY (20)
    { id: "excalibur_multiplier", name: "Excalibur Multiplier", rarity: "Legendary" },
    { id: "dino_multiplier", name: "Dino Multiplier", rarity: "Legendary" },
    { id: "satellite_multiplier", name: "Satellite Multiplier", rarity: "Legendary" },
    { id: "scissor_multiplier", name: "Scissor Multiplier", rarity: "Legendary" },
    { id: "roboshark_multiplier", name: "Roboshark Multiplier", rarity: "Legendary" },
    { id: "ruby_dropper", name: "Ruby Dropper", rarity: "Legendary" },
    { id: "amethyst_dropper", name: "Amethyst Dropper", rarity: "Legendary" },
    { id: "butterfly_furnace", name: "Butterfly Furnace", rarity: "Legendary" },
    { id: "kraken_furnace", name: "Kraken Furnace", rarity: "Legendary" },
    { id: "clione_multiplier", name: "Clione Multiplier", rarity: "Legendary" },
    { id: "tome_furnace", name: "Tome Furnace", rarity: "Legendary" },
    { id: "topaz_dropper", name: "Topaz Dropper", rarity: "Legendary" },
    { id: "volcanic_furnace", name: "Volcanic Furnace", rarity: "Legendary" },
    { id: "leek_multiplier", name: "Leek Multiplier", rarity: "Legendary" },
    { id: "market_pliers_multiplier", name: "Market Pliers Multiplier", rarity: "Legendary" },
    { id: "sugilite_dropper", name: "Sugilite Dropper", rarity: "Legendary" },
    { id: "moai_multiplier", name: "Moai Multiplier", rarity: "Legendary", isJunkyard: true },
    { id: "junk_multiplier", name: "Junk Multiplier", rarity: "Legendary", isJunkyard: true },
    { id: "birdhouse_dropper", name: "Birdhouse Dropper", rarity: "Legendary", isJunkyard: true },
    { id: "beetle_multiplier", name: "Beetle Multiplier", rarity: "Legendary", isJunkyard: true },

    // MYTHICAL (15)
    { id: "laser_sword_multiplier", name: "Laser Sword Multiplier", rarity: "Mythical" },
    { id: "hot_air_balloon_adder", name: "Hot Air Balloon Adder", rarity: "Mythical" },
    { id: "jester_dropper", name: "Jester Dropper", rarity: "Mythical" },
    { id: "phoenix_furnace", name: "Phoenix Furnace", rarity: "Mythical" },
    { id: "gramophone_dropper", name: "Gramophone Dropper", rarity: "Mythical" },
    { id: "ghosdeeri_multiplier", name: "Ghosdeeri Multiplier", rarity: "Mythical" },
    { id: "jade_dropper", name: "Jade Dropper", rarity: "Mythical" },
    { id: "waterfall_multiplier", name: "Waterfall Multiplier", rarity: "Mythical" },
    { id: "malevolent_furnace", name: "Malevolent Furnace", rarity: "Mythical" },
    { id: "honeycomb_multiplier", name: "Honeycomb Multiplier", rarity: "Mythical" },
    { id: "war_plane_multiplier", name: "War Plane Multiplier", rarity: "Mythical" },
    { id: "lion_multiplier", name: "Lion Multiplier", rarity: "Mythical" },
    { id: "tornado_furnace", name: "Tornado Furnace", rarity: "Mythical" },
    { id: "windmill_multiplier", name: "Windmill Multiplier", rarity: "Mythical", isJunkyard: true },
    { id: "car_wash_adder", name: "Car Wash Adder", rarity: "Mythical", isJunkyard: true }
];

window.MUTATIONS = MUTATIONS;
window.BASE_ITEMS = BASE_ITEMS;
